apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.giropops.name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.giropops.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.giropops.repo }}
    targetRevision: {{ .Values.giropops.revision }}
    path: {{ .Values.giropops.path }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
