{{ if .Values.argocd.giropopsSenhas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  destination:
    namespace: giropops-senhas
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
      - name: "giropopsSenhas.replicas"
        value: "{{ .Values.argocd.giropopsSenhas.replicas }}"
    path: giropops-senhas/helm
    repoURL: 'https://github.com/maxaraujo2020/descomplicando-argocd.git'
    targetRevision: feature/argocd-training
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{ end }}
