{{ if .Values.argocd.giropopsSenhas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: 'default'
  source:
    helm:
      parameters:
      - name: "giropopsSenhas.replicas"
        value: "{{ .Values.argocd.giropopsSenhas.replicas }}"
    path: giropops-senhas/helm
    repoURL: https://github.com/maxaraujo2020/descomplicando-argocd.git
    targetRevision: feature/argocd-training
  destination:
    namespace: giropops-senhas
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true # => Obriga a utilização do repo como fonte única das informações.
    syncOptions:
    - CreateNamespace=true
{{ end }}