{{ if .Values.argocd.randomLogger.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-logger
  namespace: argocd
spec:
  destination:
    namespace: random-logger
    server: https://kubernetes.default.svc
  project: default
  source:
    path: random-logger/helm
    repoURL: https://github.com/maxaraujo2020/descomplicando-argocd.git
    targetRevision: feature/argocd-training
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
{{ end }}